export type Feature = {
  key: string
  desc: string
  group: FeatureGroup
}

export type FeatureGroup =
  | 'Site Features'
  | 'L2C — Lead to Core'
  | 'New Scheduler'
  | 'Site Features (Radio)'
  | 'Account Settings'

export const FEATURE_GROUPS: FeatureGroup[] = [
  'Site Features',
  'L2C — Lead to Core',
  'New Scheduler',
  'Site Features (Radio)',
  'Account Settings',
]

export const FEATURES: Feature[] = [
  { key:'AutoAttach_ArtemisAPI', desc:'Enable Site Feature for Auto Attach', group:'Site Features' },
  { key:'NewInsPlanType_Medicare', desc:'Enable new Insurance Plan Type Medicare site feature', group:'Site Features' },
  { key:'STEDIMEDICALCLAIMS', desc:'Enable new Medical Claims site feature with STEDI Integration', group:'Site Features' },
  { key:'EnableSmartAssistMyToothIntegration', desc:'Enable smart assist with separate mytooth consent form checking integration', group:'Site Features' },
  { key:'TxPlanAttachment', desc:'Site Feature for Treatment Plan Attachment Prompts', group:'Site Features' },
  { key:'ESIGNUNSIGNEDPROGRESSNOTES', desc:'Enable mouse-drawn and typed e-signature options for Unsigned Progress Notes', group:'Site Features' },
  { key:'RCM_MovePatient_Phase1', desc:'Enable new Move Patient', group:'Site Features' },
  { key:'RCM_PREAUTHREQUIRED', desc:'Enable pre-auth-required for insurance estimation', group:'Site Features' },
  { key:'NewBatchClaimScreen_EnhanceForDSO', desc:'Enable New Batch Claim Screen Performance Improvements', group:'Site Features' },
  { key:'REFERRALLETTERAUTOMATION', desc:'Enable automatic AI-generated Referral Letter (Q1 2026)', group:'Site Features' },
  { key:'ENABLEAIRESTVOICE', desc:'Enable AI Restorative voice assistant', group:'Site Features' },
  { key:'REFERREDTOLAZYLOADFILTER', desc:'Enable lazy load filtering on Edit Patient — Referred To dropdown', group:'Site Features' },
  { key:'ENABLE_SIGNATURE_ARCHIVE', desc:'Enable signature data archival', group:'Site Features' },
  { key:'UNSIGNEDPROGRESSNOTESNEWUI', desc:"Enable new UI for the 'Unsigned Progress Notes Report' workflow", group:'Site Features' },
  { key:'CKEDITOR5UPGRADE', desc:'Enable CKEditor5 upgrade across Denticon screens that support text formatting', group:'Site Features' },
  { key:'RCM_EstEngine_CodeBundling', desc:'Enable Estimation Engine Code Bundling', group:'Site Features' },
  { key:'ENABLEAGENTMESSAGE', desc:'Enable Agent Messages for TWC and MH', group:'Site Features' },
  { key:'REDUCEDATADENSITY_PATIENTARCHIVE', desc:'Enable reduce data density in patient search', group:'Site Features' },
  { key:'RCM_Transfer_Credit', desc:'Enable transfer credit feature', group:'Site Features' },
  { key:'ENABLE_TOPNAV_SECONDARY', desc:'Enable new Secondary Top Navigation bar', group:'Site Features' },
  { key:'ENABLE_TOPNAV_PRIMARY', desc:'Enable new Primary Top Navigation bar', group:'Site Features' },
  { key:'CREATEPROGRESSNOTESNEWUI', desc:"Enable new UI for all 'Create Progress Notes' workflows (Q4 2025)", group:'Site Features' },
  { key:'ENABLENEWTOPNAVIGATION', desc:'Enable new top navigation', group:'Site Features' },
  { key:'ENABLEAIPERIOVOICE', desc:'Enable AI Perio voice assistant', group:'Site Features' },
  { key:'RCM_StmtService_BackgroundJob', desc:'Site feature for statement background job', group:'Site Features' },
  { key:'REFPORTALENHANCEMENTS', desc:'Site Feature for Referral Portal Enhancement', group:'Site Features' },
  { key:'LEDGERMODALSNEWUI', desc:'Enable new UI for the Ledger items modals', group:'Site Features' },
  { key:'RCM_EstEngine_WholeMouthFreq', desc:'Enable Estimation Engine Whole Mouth Frequency', group:'Site Features' },
  { key:'RCM_EstEngine_MissingThClause', desc:'Enable Estimation Engine Missing Tooth Clause', group:'Site Features' },
  { key:'RCM_EstEngine_PerDayQuantity', desc:'Enable Estimation Engine Per Day Quantity', group:'Site Features' },
  { key:'OVERJETINTEGRATION', desc:'Enable bridge from Denticon to Overjet imaging solution', group:'Site Features' },
  { key:'ZENTIST_INTEGRATION', desc:'Enable Zentist Integration', group:'Site Features' },
  { key:'REDUCEDATADENSITY_PATIENTRECALL', desc:'Enable Reduce Data Density for Patient Recall', group:'Site Features' },
  { key:'ENABLETREATMENTPLANPRESENTATION', desc:'Enable Treatment Plan Presentation', group:'Site Features' },
  { key:'RCM_ESTENGINE_FREQACROSSCODES', desc:'Enable frequency limitation across codes for insurance estimation', group:'Site Features' },
  { key:'RCM_ESTENGINE_AGELIMITATION', desc:'Enable minimum age limitation for insurance estimation', group:'Site Features' },
  { key:'ECLAIM_AUTOMATION_INPROGRESS', desc:'EClaim Automation - In Progress', group:'Site Features' },
  { key:'ECLAIM_AUTOMATION', desc:'EClaim Automation', group:'Site Features' },
  { key:'MEDICAL_HISTORY_ARCHIVE', desc:'Enable medical history data archival', group:'Site Features' },
  { key:'ALIGN_INSOVERPAY_LOGIC_LEGACYANDV4', desc:'Align legacy and advanced v4 screens insurance overpayment allocation logic', group:'Site Features' },
  { key:'MEDICALCLAIMDEFECT4634', desc:'Medical Claim Defect 4634', group:'Site Features' },
  { key:'DENTICONINSIGHTSSCHEDULER', desc:'Display Appointment No Show Insight scores in Scheduler', group:'Site Features' },
  { key:'DENTICONINSIGHTS', desc:'Enable Denticon Insights', group:'Site Features' },
  { key:'ENABLEREALTIMEBATCHPROCESSING', desc:'Site feature for processing batch claim in real time', group:'Site Features' },
  { key:'ENABLE_835HUB', desc:'Site Feature for 835 Hub', group:'Site Features' },
  { key:'ENABLEPATPORTALOPTIMIZEDLOGIN', desc:'Site Feature for Patient Portal signup and login optimization', group:'Site Features' },
  { key:'RECONCILE835_SCREEN', desc:'Show reconcile 835 screen', group:'Site Features' },
  { key:'CONVERSION_DATA_MAPPING_UTILITY', desc:'Enable Data Conversion Mapping', group:'Site Features' },
  { key:'PROGRESSNOTESSIGNATUREUPDATE', desc:'Progress Notes Signature Verification', group:'Site Features' },
  { key:'ENABLEALLOCATIONUTILITYFIXESBETA', desc:'Enable Allocation Utility Fixes Beta', group:'Site Features' },
  { key:'ENABLEENHANCEDTASKMAGDXCSTATUS', desc:'Enhanced Task Manager - DXC Status integration', group:'Site Features' },
  { key:'ENABLECARESTREAMV8', desc:'Enable Carestream V8', group:'Site Features' },
  { key:'ENABLEGETAPPTDETAILSOPTIMIZATION', desc:'Enable Get App Details Optimization', group:'Site Features' },
  { key:'ENABLEREPORTSSURCHARGE', desc:'Enable Reports Surcharge site feature', group:'Site Features' },
  { key:'ENABLENEWBATCHCLAIMSCREEN', desc:'Enable New Batch Claims Screen', group:'Site Features' },
  { key:'ENABLEHEALTHFORMS', desc:'Enable Health Forms', group:'Site Features' },
  { key:'ENABLEFEESCHEDULELAZYLOADFILTER', desc:'Enable lazy load filtering in fee schedule', group:'Site Features' },
  { key:'ENABLEDXCVALIDATIONAPI', desc:'Enable new DXC Validation API', group:'Site Features' },
  { key:'ENABLEBLOCKRPA', desc:'Enable Block RPA', group:'Site Features' },
  { key:'ENABLEADVANCEDMISCSETUP', desc:'Enable Advanced Misc Setup', group:'Site Features' },
  { key:'ENABLEOPTIMIZEDFINDSLOT', desc:'Enable Optimized FindSlot SP', group:'Site Features' },
  { key:'ENABLEBETACLIENTFORINSPAYMENT', desc:'Enable IsBetaClient using site-feature', group:'Site Features' },
  { key:'ENABLESERVICEFEEFORPGID', desc:'Enable Service Fee for PGIDs using site-feature', group:'Site Features' },
  { key:'ENABLEEPAD', desc:'Enable EPad for Signature', group:'Site Features' },
  { key:'ENABLECREDITCARDSTMT', desc:'Enable Credit card box in statement', group:'Site Features' },
  { key:'ENABLEADDEDITAPPTSLOWNESSFIX', desc:'Enable AddEditAppointment Slowness Fix', group:'Site Features' },
  { key:'ENABLERTEHIERACHYCHECK', desc:'Check correct hierarchy level based on DXC feedback', group:'Site Features' },
  { key:'ENABLEAMBMISSINGLOGICFIX', desc:'Enable AMB Logic Missing Fix', group:'Site Features' },
  { key:'ENABLESSOSETUP', desc:'Enable Single Sign On Setup', group:'Site Features' },
  { key:'ENABLEADVANCEDSETUPSECURITY', desc:'Enable Advanced Setup Security', group:'Site Features' },
  { key:'ENABLEMESSAGINGSERVICE', desc:'Enable Messaging Service', group:'Site Features' },
  { key:'ENABLEBATCHADDFLASHALERTS', desc:'Enable Batch Add Flash Alerts', group:'Site Features' },
  { key:'ENABLECONVERSIONENVIRONMENT', desc:'Enable Conversion environment for a given PGID', group:'Site Features' },
  { key:'ENABLEADVANCEDCHARTINGPROGRESSNOTESTAB', desc:'Enable Advanced Progress Notes Tab of Advanced Charting', group:'Site Features' },
  { key:'ENABLEADVANCEDCHARTINGXRAYTAB', desc:'Enable Advanced X-Ray Tab of Advanced Charting', group:'Site Features' },
  { key:'ENABLEDAOFWIPLANEMULATOR', desc:'Enable DA of WI Plan Emulator', group:'Site Features' },
  { key:'ENABLESKYGEN270INTEGRATION', desc:'Enable SkyGen Integration for Eligibility checks', group:'Site Features' },
  { key:'ENABLESKYGEN837INTEGRATION', desc:'Enable SkyGen Integration for 837 claims', group:'Site Features' },
  { key:'ENABLESENDGRIDREGISTRATION', desc:'Enable SendGrid Email Registration', group:'Site Features' },
  { key:'ENABLEDPETEMPLATESYNC', desc:'Provide flexibility to copy template for active patient engagement PGID', group:'Site Features' },
  { key:'ENABLEINVALIDSURFCHECK', desc:'Enable invalid Surfaces check for charting', group:'Site Features' },
  { key:'ENABLEINTERNALFINANCINGSUBTYPE', desc:'Enable Internal Financing Subtype', group:'Site Features' },
  { key:'ENABLEDENTALINSDETACH', desc:'Enable Dental Insurance Detach', group:'Site Features' },
  { key:'ENABLEFINANCIALAGREEMENTCASHDISCOUNT', desc:'Enable Financial Agreement Cash Discount', group:'Site Features' },
  { key:'ENABLEOPENEDGEPARTIALREFUND', desc:'Enable OpenEdge Partial Refund', group:'Site Features' },
  { key:'ENABLETOOTHFILTERONRESTCHART', desc:'Enable Tooth Filter On Restorative Charting', group:'Site Features' },
  { key:'ENABLEPRACTICEANALYTICS', desc:'Enable Denticon Practice Analytics', group:'Site Features' },
  { key:'ENABLEEXCLUDEBILLINGPROVIDER', desc:'Exclude Billing Provider in Transactions', group:'Site Features' },
  { key:'ENABLEOPENEDGERCMSTATUSCHECK', desc:'Enable RCM status check for OpenEdge Transactions', group:'Site Features' },
  { key:'ENABLEUNARCHIVEONLINEREGISTEREDPATIENTS', desc:'Enable Unarchive Online Registered Patients Screen', group:'Site Features' },
  { key:'ENABLEINSPAYMVCV4', desc:'Enable New Insurance Payment Entry (MVC) Version 4', group:'Site Features' },
  { key:'ENABLESEXTANT', desc:'Enable Sextant', group:'Site Features' },
  { key:'ENABLEATHENA', desc:'Enable Athena HealthCare', group:'Site Features' },
  { key:'ENABLEMODELOFFICEPHONENUMBER', desc:'Enable model office phone number for OID (vs unique phone number)', group:'Site Features' },
  { key:'VBS30', desc:'VBS 3.0 - BPK', group:'Site Features' },
  { key:'RADIUSGLOBAL', desc:'Radius Global Hookup', group:'Site Features' },
  { key:'ENABLECHC', desc:'Enable Change Healthcare', group:'Site Features' },
  { key:'ENABLECARECREDIT', desc:'Enable Care Credit', group:'Site Features' },
  { key:'ENABLEMOUTHWATCHINTEGRATION', desc:'Enable Mouthwatch Integration', group:'Site Features' },
  { key:'ENABLECONTRACTNEW', desc:'Enable Contract New', group:'Site Features' },
  { key:'ENABLEOPENEDGE', desc:'Enable Open Edge', group:'Site Features' },
  { key:'ENABLEDENTALXCHANGECLAIMATTACHMENT', desc:'Enable DentalxChange Claim Attachment', group:'Site Features' },
  { key:'VALIDATEPATADDRESS', desc:'Validate addresses of patient and responsible party', group:'Site Features' },
  { key:'ENABLEORTHOTXCARD', desc:'Enable Ortho Treatment Card', group:'Site Features' },
  { key:'WriteOff', desc:'Transaction Screen Write Off', group:'Site Features' },
  { key:'Refund', desc:'Transaction Screen Refund Control', group:'Site Features' },
  { key:'TransferCredits', desc:'Transaction Screen Transfer Credits', group:'Site Features' },
  { key:'ENABLEADVANCEDSETUP', desc:'Enable Advanced Setup', group:'Site Features' },
  { key:'EnableSchdrAutoRefresh', desc:'Enable Scheduler Auto Refresh', group:'Site Features' },
  { key:'ENABLEREPORTSCHEDULING', desc:'Enable Report Scheduling', group:'Site Features' },
  { key:'RTENewView', desc:'New RTE view from Denticon', group:'Site Features' },
  { key:'ENABLERX2018', desc:'Enable RX 2018', group:'Site Features' },
  { key:'DENTILYTICSBASIC', desc:'Enable Dentilytics Basic', group:'Site Features' },
  { key:'LegWork', desc:'LegWork integration', group:'Site Features' },
  { key:'ENABLETIMEZONEWISEDATECONVERSION', desc:'Enable Time Zone Wise Date-Time Conversion', group:'Site Features' },
  { key:'Solution Reach', desc:'Solution Reach integration', group:'Site Features' },
  { key:'DEMANDFORCE', desc:'Demand Force integration', group:'Site Features' },
  { key:'ENABLEMULTIPGIDUSERCREATE', desc:'Enable access to Multi PGID create page', group:'Site Features' },
  { key:'ENABLEDMDONLINESETUP', desc:'Enable MD-Online Setup', group:'Site Features' },
  { key:'DENTICONVBS', desc:'Denticon VBS 2.0', group:'Site Features' },
  { key:'ALLOW99PROCSPERCLAIM', desc:'Allow 99 Procedures Per Claim', group:'Site Features' },
  { key:'RELATIVEFEESCHEDULEPCT', desc:'Enable Relative Fee Schedule Percentage', group:'Site Features' },
  { key:'DENTILYTICS', desc:'Dentilytics', group:'Site Features' },
  { key:'CLAIMGROUPQTY', desc:'Group QTY on ADA 2012 Form', group:'Site Features' },
  { key:'SUPRESSCODEINSTMT', desc:'Suppress code in statement', group:'Site Features' },
  { key:'VX805', desc:'Enable the TransFirst VX805 device instead of the USB card reader', group:'Site Features' },
  { key:'ENABLE835', desc:'Enable Process 835', group:'Site Features' },
  { key:'ENABLEEHR', desc:'Enables EHR menus', group:'Site Features' },
  { key:'LOYGEN', desc:'LoyGen SSO', group:'Site Features' },
  { key:'DENTISTASCEO', desc:'Dentist As A CEO', group:'Site Features' },
  { key:'MEDICALCLAIMS', desc:'Enable Medical EClaims by PGID', group:'Site Features' },
  { key:'USESERVERTIMEZONE', desc:'Use server time zone - do not convert to local time for showing datetimes', group:'Site Features' },
  { key:'PRDREFFSCHED', desc:'Enables provider effective schedules in scheduler', group:'Site Features' },
  { key:'APPTAUTOSENDSMS', desc:'Auto-send SMS text messages (scheduled job runs on subscriber every night)', group:'Site Features' },
  { key:'APPTAUTOCONFIRM', desc:'Auto-confirm appointments (scheduled job runs on subscriber every night)', group:'Site Features' },
  { key:'TRANSWORLD', desc:'Transworld Hookup', group:'Site Features' },
  { key:'INSLIMITATIONS', desc:'Show Insurance Limitations By PGID', group:'Site Features' },
  { key:'QBVBSVERIFY', desc:'VBS Subscriber Insurance Verification', group:'Site Features' },
  { key:'ENABLEL2C_TRANSACTIONENTRY', desc:'Enable Transaction Entry Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_BATCHINSURANCEPAYMENT', desc:'Enable Batch Insurance Payment Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_BATCHPATIENTPAYMENT', desc:'Enable Batch Patient Payment Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PREAUTHLIST', desc:'Enable Pre-Authorization List Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_TREATMENTPLAN', desc:'Enable Treatment Plan Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ACCOUNTLEDGER', desc:'Enable Ledger Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_CAPITATIONPAYMENT', desc:'Enable Capitation Payment Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_INSURANCEPAYMENTV4', desc:'Enable Insurance Payment Entry v4 - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_INSURANCEPAYMENTENTRY', desc:'Enable Insurance Payment Entry Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PERIOCHART', desc:'Enable Perio Chart Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ADVANCEDCHARTING', desc:'Enable Advanced Charting Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_RESTORATIVECHARTING', desc:'Enable Restorative Charting Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_AIASSISTOVERVIEW', desc:'Enable AI Assist Overview Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_RESTORATIVECHARTINGMATERIALS', desc:'Enable Restorative Charting Materials Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_NOTESMACRO', desc:'Enable Notes Macro Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PAYMENT_ADJUSTMENTTYPE', desc:'Enable Payment/Adjustment Type Setup - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_MISCSETUP', desc:'Enable Misc Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PRESCRIPTIONSSETUP', desc:'Enable Prescriptions Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PICKLIST', desc:'Enable PickList Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_COLLECTIONAGENCY', desc:'Enable Collection Agency Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PERIOSETUPTEMPLATES', desc:'Enable Perio Setup Templates Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_COLLECTIVELETTERS', desc:'Enable Collection Letters Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_SEARCHPATIENT', desc:'Enable Search Patient Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PATIENTOVERVIEW', desc:'Enable Patient Overview Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_FLASHALERTS', desc:'Enable Flash Alerts Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_RECALLDUEDATES', desc:'Enable Recall Due Dates Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PATIENTPORTALSIGNUPS', desc:'Enable Patient Portal Signups Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_EDITPATIENTINFO', desc:'Enable Edit Patient Info Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ADDLINKORTHOPATIENT', desc:'Enable Add/Link Patient Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_REGULARPAYMENTPLAN', desc:'Enable Regular Payment Plan Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ORTHOPAYMENTPLAN', desc:'Enable Ortho Payment Plan Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_BASICMEASUREMENT', desc:'Enable Basic Measurement Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_UNARCHIVEONLINEREGISTEREDPATIENT', desc:'Enable Online Registered Patient Unarchive Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_EXISTINGONLINEREGISTEREDPATIENT', desc:'Enable Online Registered Patient Existing Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_NEWONLINEREGISTEREDPATIENT', desc:'Enable Online Registered Patient New Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ICDCODESBOOTSTRAP', desc:'Site Feature for Bootstrap POC', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PATIENTMEDICALHISTORY', desc:'Enable Patient Medical History Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_DENTALFILLOUTFORM', desc:'Enable Dental Fillout Form Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_MEDICALFILLOUTFORM', desc:'Enable Medical Fillout Form Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PRESCRIPTIONS', desc:'Enable Prescriptions Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ASSIGN2RESTRICTEDUSERS', desc:'Enable Assign to Restricted Users Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PATIENTNOTES', desc:'Enable Patient Notes Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_CHANGEHOMEOFFICE', desc:'Enable Change Home Office Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_REALLOCATEACCOUNT', desc:'Enable Reallocate Account Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PATIENTCARIESRISKASSESSMENT', desc:'Enable Patient Caries Risk Assessment Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PATIENTADDRESSES', desc:'Enable Patient Addresses Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_RESTORATIVECHARTINGCOLORSETUP', desc:'Enable Restorative Charting Color Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_REFERRALSETUP', desc:'Enable Referral Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_EMPLOYERSSETUP', desc:'Enable Employers Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ORTHOTREATMENTCARDTRANSACTIONS', desc:'Enable Ortho Treatment Card Transactions Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_STATUSTRACKERPATIENT', desc:'Enable Status Tracker Patient Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_UNCLOSEACCOUNTSTATEMENTPATIENT', desc:'Enable Unclosed Account Statement Patient Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_TYPEOFSERVICECODESSETUP', desc:'Enable Type Of Service Codes Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_PLACEOFSERVICECODESSETUP', desc:'Enable Place Of Service Codes Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_MODIFIERCODESSETUP', desc:'Enable Modifier Codes Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_REFERRALDEMOGRAPHICSSETUP', desc:'Enable Referral Demographics Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_EXPLOSIONCODESSETUP', desc:'Explosion Codes Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_ICDCODESSETUP', desc:'Enable ICD Codes Setup Screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLEL2C_CLOSEOUT', desc:'Enable Close Out screen - Fully Core Version', group:'L2C — Lead to Core' },
  { key:'ENABLELEGACYTOCORESESSIONSYNC', desc:'Enable Legacy to Core Session Sync', group:'L2C — Lead to Core' },
  { key:'NEWSCHED_APPTS_CARECREDITINFO', desc:'Site Feature for New Sched Care Credit Info by Appointment', group:'New Scheduler' },
  { key:'NEWSCHED_PROVIDERSCHEDULESLOTSTEMPLATESBYUSERVIEW', desc:'Site Feature for New Sched get Provider Schedule Slots Templates by User View', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_DELETE', desc:'Site Feature for New Sched Appointment Delete', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_CHANGESTATUS', desc:'Site Feature for New Sched Appointment Change Status', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_CUTPASTE', desc:'Site Feature for New Sched Appointment Cut Paste', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_COPYPASTE', desc:'Site Feature for New Sched Appointment Copy Paste', group:'New Scheduler' },
  { key:'NEWSCHED_PUTOFFICESCHEDULES', desc:'Site Feature for New Sched office schedules cache update', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_WEEKLYVIEWBYUSER', desc:'Site Feature for New Sched weekly view by user appointments', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_DAILYVIEWBYUSER', desc:'Site Feature for New Sched daily view by user appointments', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_WEEKLYVIEWBYALLPROVIDERS', desc:'Site Feature for New Sched weekly view by all providers appointments', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_WEEKLYVIEWBYPROVIDER', desc:'Site Feature for New Sched weekly view by provider appointments', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_DAILYVIEWBYALLPROVIDERS', desc:'Site Feature for New Sched daily view by all providers appointments', group:'New Scheduler' },
  { key:'NEWSCHED_APPTS_DAILYVIEWBYPROVIDER', desc:'Site Feature for New Sched daily view by provider appointments', group:'New Scheduler' },
  { key:'NEWSCHED_PROVIDERSCHEDULESLOTSBYUSERVIEW', desc:'Site Feature for New Sched get Provider Schedule Slots by User View', group:'New Scheduler' },
  { key:'NEWSCHED_PROVIDERSCHEDULESLOTSTEMPLATES', desc:'Site Feature for New Sched get Provider Slots Templates', group:'New Scheduler' },
  { key:'NEWSCHED_PROVIDERSCHEDULESLOTS', desc:'Site Feature for New Sched get Provider Slots', group:'New Scheduler' },
  { key:'NEWSCHED_GETPROVIDERHOLIDAYSBYSCHEDVIEW', desc:'Site Feature for New Sched get provider holidays by schedule view', group:'New Scheduler' },
  { key:'NEWSCHED_SCHEDVIEWSBYID', desc:'Site Feature for New Sched get scheduler views', group:'New Scheduler' },
  { key:'NEWSCHED_GETPROVIDERSCHEDBYOPR', desc:'Site Feature for New Sched get provider schedule by operator', group:'New Scheduler' },
  { key:'NEWSCHED_GETPROVIDERHOLIDAYS', desc:'Site Feature for New Sched get provider holidays', group:'New Scheduler' },
  { key:'NEWSCHED_GETOPERATORIES', desc:'Site Feature for New Sched get office operatories', group:'New Scheduler' },
  { key:'NEWSCHED_GETOFFICESCHEDULE', desc:'Site Feature for New Sched get office schedule', group:'New Scheduler' },
  { key:'NEWSCHED_GETOFFICEHOLIDAYS', desc:'Site Feature for New Sched get office holidays', group:'New Scheduler' },
  { key:'Alpha Account', desc:'Alpha Account site feature', group:'Site Features (Radio)' },
  { key:'Enable Multiple Quantity ADA', desc:'Enable Multiple Quantity ADA', group:'Site Features (Radio)' },
  { key:'Enable Nightly RTE Check', desc:'Enable Nightly Real-Time Eligibility Check', group:'Site Features (Radio)' },
  { key:'Medical Claims [Inovalon]', desc:'Enable Medical Claims via Inovalon integration', group:'Site Features (Radio)' },
  { key:'Automated Campaigns', desc:'Enable Automated Campaigns (Yes/No)', group:'Account Settings' },
  { key:'Planet DDS Pay Surcharge', desc:'Enable Planet DDS Pay Surcharge (Yes/No)', group:'Account Settings' },
  { key:'Sunbit Integration', desc:'Enable Sunbit patient financing integration (Yes/No)', group:'Account Settings' },
  { key:'Quick Fill', desc:'Enable Quick Fill scheduling feature (Yes/No)', group:'Account Settings' },
  { key:'Smart Assist', desc:'Enable Smart Assist AI features (Yes/No)', group:'Account Settings' },
  { key:'Xchart Vital Monitoring', desc:'Enable Xchart Vital Monitoring integration (Yes/No)', group:'Account Settings' },
  { key:'Realtime Preadjudication Integration', desc:'Enable Realtime Preadjudication Integration (Yes/No)', group:'Account Settings' },
  { key:'EDI Vendor (Clearinghouse)', desc:'Set EDI/Clearinghouse vendor (e.g. EHG, DXC)', group:'Account Settings' },
  { key:'Account (Enterprise/Solo/Mobile)', desc:'Set account type: Enterprise, Solo, or Mobile', group:'Account Settings' },
  { key:'Credit Insurance Overpayment to Patient', desc:'Enable credit insurance overpayment allocation to patient (Yes/No)', group:'Account Settings' },
]
