/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@planetdds/ui/src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@planetdds/ui/dist/**/*.{js,mjs}',
  ],
  safelist: [
    '!hidden', 'md:!flex', 'md:!flex-row', 'md:!hidden', 'md:!items-center',
    'md:!items-end', 'md:!static', 'md:!block', 'md:!w-0', 'md:!gap-3',
    'md:!px-8', 'md:!py-3', 'md:!border-t-0', 'md:!border-b',
    'sm:!items-center', 'sm:!p-8', 'sm:!overflow-y-visible', 'sm:!rounded-none',
    'xs:!flex-row', 'xs:!block', 'xs:!hidden', '!items-end', 'flex-col-reverse',
    'md:!p-6', 'md:!w-auto', 'md:!w-[280px]', 'md:!rounded-r-xl',
    'md:!border-l-0', 'md:!w-[239px]', 'md:!border-t', 'md:!rounded-l-none',
    'md:!rounded-b-none', 'md:!relative', '!truncate', 'grid-cols-1!',
    'max-md:hidden', 'max-w-100', 'shadow-border-secondary',
  ],
  theme: {
    extend: {
      screens: { 'xs': '600px' },
      backgroundColor: {
        'primary': 'var(--colors-background-bg-primary-light-mode, hotpink)',
        'brand-solid': 'var(--colors-background-bg-brand-solid-light-mode, hotpink)',
        'brand-solid_hover': 'var(--colors-background-bg-brand-solid_hover-light-mode, hotpink)',
        'disabled': 'var(--colors-background-bg-disabled-light-mode, hotpink)',
        'disabled_subtle': 'var(--colors-background-bg-disabled_subtle-light-mode, hotpink)',
        'secondary': 'var(--colors-background-bg-secondary-light-mode, hotpink)',
        'secondary_hover': 'var(--colors-background-bg-secondary_hover-light-mode, hotpink)',
        'error-primary': 'var(--colors-background-bg-error-primary-light-mode, hotpink)',
        'error-primary_hover': 'var(--colors-background-bg-error-primary_hover-light-mode, hotpink)',
        'error-solid': 'var(--colors-background-bg-error-solid-light-mode, hotpink)',
        'error-solid_hover': 'var(--colors-background-bg-error-solid_hover-light-mode, hotpink)',
        'success-solid': 'var(--colors-background-bg-success-solid-light-mode, hotpink)',
      },
      textColor: {
        'white': '#ffffff',
        'primary': 'var(--colors-text-text-primary-900-light-mode, hotpink)',
        'secondary': 'var(--colors-text-text-secondary-700-light-mode, hotpink)',
        'secondary_hover': 'var(--colors-text-text-secondary_hover-light-mode, hotpink)',
        'tertiary': 'var(--colors-foreground-fg-tertiary-600-light-mode, hotpink)',
        'quaternary': 'var(--colors-foreground-fg-quaternary-400-light-mode, hotpink)',
        'placeholder': 'var(--colors-text-text-placeholder-light-mode, hotpink)',
        'disabled': 'var(--colors-text-text-disabled-light-mode, hotpink)',
        'brand-tertiary': 'var(--colors-text-text-brand-tertiary-600-light-mode, hotpink)',
        'error-primary': 'var(--colors-text-text-error-primary-600-light-mode, hotpink)',
        'error-primary_hover': 'var(--colors-text-text-error-primary_hover-light-mode, hotpink)',
        'fg-white': 'var(--colors-foreground-fg-white-light-mode, hotpink)',
        'fg-quaternary': 'var(--colors-foreground-fg-quaternary-400-light-mode, hotpink)',
        'fg-quaternary_hover': 'var(--colors-foreground-fg-quaternary_hover-light-mode, hotpink)',
        'fg-disabled': 'var(--colors-foreground-fg-disabled-light-mode, hotpink)',
        'fg-disabled_subtle': 'var(--colors-foreground-fg-disabled_subtle-light-mode, hotpink)',
        'fg-error-secondary': 'var(--colors-foreground-fg-error-secondary-light-mode, hotpink)',
        'button-primary-icon': 'var(--colors-foreground-fg-primary_on-brand-light-mode, hotpink)',
        'button-primary-icon_hover': 'var(--colors-foreground-fg-primary_on-brand-light-mode, hotpink)',
        'button-secondary-color': 'var(--colors-foreground-fg-secondary-700-light-mode, hotpink)',
        'button-secondary-color_hover': 'var(--colors-foreground-fg-secondary_hover-light-mode, hotpink)',
        'button-primary-error': 'var(--colors-foreground-fg-error-primary-light-mode, hotpink)',
      },
      ringColor: {
        'transparent': 'transparent',
        'primary': 'var(--colors-border-border-primary-light-mode, hotpink)',
        'brand': 'var(--colors-border-border-brand-light-mode, hotpink)',
        'disabled': 'var(--colors-border-border-disabled-light-mode, hotpink)',
        'disabled_subtle': 'var(--colors-border-border-disabled_subtle-light-mode, hotpink)',
        'secondary': 'var(--colors-border-border-secondary-light-mode, hotpink)',
        'bg-brand-solid': 'var(--colors-background-bg-brand-solid-light-mode, hotpink)',
        'error': 'var(--colors-border-border-error-light-mode, hotpink)',
        'error_subtle': 'var(--colors-border-border-error_subtle-light-mode, hotpink)',
      },
      maxWidth: {
        'container': 'var(--max-width-container, 1280px)',
        '100': '25rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
      },
      boxShadowColor: {
        'border-secondary': 'var(--colors-border-border-secondary-light-mode, #d5d7da)',
      },
      colors: {
        brand: {
          25: 'var(--brand25)', 50: 'var(--brand50)', 100: 'var(--brand100)',
          200: 'var(--brand200)', 300: 'var(--brand300)', 400: 'var(--brand400)',
          500: 'var(--brand500)', 600: 'var(--brand600)', 700: 'var(--brand700)',
          800: 'var(--brand800)', 900: 'var(--brand900)', 950: 'var(--brand950)',
        },
        gray: {
          25: 'var(--grayLightMode25)', 50: 'var(--grayLightMode50)', 100: 'var(--grayLightMode100)',
          200: 'var(--grayLightMode200)', 300: 'var(--grayLightMode300)', 400: 'var(--grayLightMode400)',
          500: 'var(--grayLightMode500)', 600: 'var(--grayLightMode600)', 700: 'var(--grayLightMode700)',
          800: 'var(--grayLightMode800)', 900: 'var(--grayLightMode900)', 950: 'var(--grayLightMode950)',
        },
        error: {
          25: 'var(--error25)', 50: 'var(--error50)', 100: 'var(--error100)',
          200: 'var(--error200)', 300: 'var(--error300)', 400: 'var(--error400)',
          500: 'var(--error500)', 600: 'var(--error600)', 700: 'var(--error700)',
          800: 'var(--error800)', 900: 'var(--error900)', 950: 'var(--error950)',
        },
        overlay: '#0a0d12',
        success: {
          25: 'var(--success25)', 50: 'var(--success50)', 100: 'var(--success100)',
          200: 'var(--success200)', 300: 'var(--success300)', 400: 'var(--success400)',
          500: 'var(--success500)', 600: 'var(--success600)', 700: 'var(--success700)',
          800: 'var(--success800)', 900: 'var(--success900)', 950: 'var(--success950)',
        },
      },
    },
  },
  plugins: [
    require('tailwindcss-react-aria-components')({ prefix: 'in' }),
    require('tailwindcss-animate'),
  ],
}
